### ISSUE TITLE
Upgrading to Cropper.js v2.3.4

### ISSUE THREAD

**Issue by muskie9** [willmorgan/silverstripe-cropperfield#13]
@willmorgan would there need to be a new branch if a PR for this would be submitted? I've been working through the latest tag of the plugin and many of the plugin options have changed.

I'm working to see how feasible it is to get the default options to function the same as the current version, but some things may have been dropped so in that respect there would be breaking changes.

**Comment by muskie9** [comment]
@willmorgan would there need to be a new branch if a PR for this would be submitted? I've been working through the latest tag of the plugin and many of the plugin options have changed.

I'm working to see how feasible it is to get the default options to function the same as the current version, but some things may have been dropped so in that respect there would be breaking changes.

**Comment by willmorgan** [comment]
@muskie9 Thanks for doing this. Yes, a new semver branch would need to be created but I could sort that for you 😄

**Comment by muskie9** [comment]
Perfect, thanks! I have most of the plugin specific things working in the cms, just working through some save issues. Hope to open a PR soon!

**Comment by willmorgan** [comment]
Cool, thanks. Just open a PR and I'll get to it as soon as I can. I will keep this issue open in the meantime.
