### ISSUE TITLE
Multiple $has_one necessary?

### ISSUE THREAD

**Issue by jonom** [willmorgan/silverstripe-cropperfield#3]
Hi Will,

I was dreaming up a module very similar to this one when I saw it released so I'm looking forward to giving this a try!

Just looking at the ReadMe though, I notice you're specifying two $has_one image relations - is this necessary in practice? It seems to me you should only need a single reference to the original image file?

Unless you're creating a new image file and db record for each crop that can then be used elsewhere in the CMS... in which case would you consider supporting the option to keep only the original image in the file store and have crops stored as meta objects? In that scenario I suppose a Page or other object could have a $has_one to a 'CroppedImage' object which doesn't extend Image, but contains cropping information and has a $has_one relation to the original Image.

This could potentially also allow for a 'choose a crop' scenario where once you've selected the original image to be used, you could browse crops already created that suit the requirements of the current CropperField.

Also thanks for the shout-out to FocusPoint. Minor correction (just FYI) - SilverStripe FocusPoint isn't actually powered by the jQuery module, it just uses the same concept for finding a crop. The SilverStripe version provides very basic art-direction for template driven destructive cropping, but can also be used in conjunction with the jQuery version to provide front-end 'responsive' cropping if desired. I want to see how I can introduce further control (i.e. allow zooming) for individual cropping contexts but not sure yet if I will try to introduce that natively or if I can just make it cooperate really well with a module like this one. I'll let you know what I work out!

**Comment by willmorgan** [comment]
Yes, it's necessary because the way SilverStripe handles resized images is really fiddly. The idea is once you've got your art direction image, you _could_ do further resizing for smaller browsers if you wanted. But I'm not really interested in working around the (imo) horrible and untracked method of having things inside a _resized folder and not tracked by the filesystem. Maybe once the filesystem RFC gets smoothed over and developed I'll revisit this approach.

> would you consider supporting the option to keep only the original image in the file store and have crops stored as meta objects?

Sure, patches welcome :wink:

**Comment by jonom** [comment]
Cool thanks for the feedback Will
