### ISSUE TITLE
Cropperfield creates New Image file, but cropped image not saved

### ISSUE THREAD

**Issue by helenclarko** [willmorgan/silverstripe-cropperfield#9]
Cropperfield looks to be working, but does not save the cropped image.
It creates a New Image file without an extension.

**Comment by dhensby** [comment]
What version of SilverStripe? Can you confirm the steps you're taking to replicate this?

**Comment by willmorgan** [comment]
Hmm, interesting. It shouldn't be doing that :wink:

Would you mind sharing some source code so I can investigate?

**Comment by helenclarko** [comment]
Hi dhensby and Wilmorgan,

So its using the latest release 3.3.1 and 0.5 release of Cropperfield.

Currently attached to HomePage;

PHP
`
<?php
class HomePage extends Page {

	private static $db = array(
	);

	private static $has_one = array(
		'Image' => 'Image',
		'MyArtDirectionCrop' => 'Image',
	);
	
	public function getCMSFields() {
		$fields = parent::getCMSFields();
			$fields->addFieldToTab("Root.Main", $uploadField = new UploadField('Image', 'Big Photo Uploader'));
			$fields->addFieldToTab("Root.Main", $cropperField = new CropperField\CropperField(
				'MyArtDirectionCrop',
				'Cropped Image',
				new CropperField\Adapter\UploadField(
					$uploadField
				)
			));
			$cropperField->aspect_ratio = 16/9;

		return $fields;
    }

}
class HomePage_Controller extends Page_Controller {



}
`

**Comment by helenclarko** [comment]
Im beginning to think this is to do with permissions over the assets folder.

**Comment by willmorgan** [comment]
> Im beginning to think this is to do with permissions over the assets folder.

@helenclarko Do you see any other errors when you try to save? Can you upload files normally? If not, try chowning the assets folder to the same user as your web server user (Apache / nginx) and try again. Failing that try 0777.

Also you will need to use `$cropperField->setOption('aspect_ratio', 16/9);` if you want that aspect ratio setting to work.

**Comment by helenclarko** [comment]
@willmorgan 

Thanks for the info on aspect ratio, that's all working.

Was able to get cropperfield working once uploaded to my server. The issue seems to be within my local test environment. I still haven't worked out what the issue is, but suspect its something to do with permissions. I'll need to check that though (using XAMPP on Windows).

Sorry for wasting you time, for now I'm happy to say this has been solved.
